### ISSUE TITLE
Add graceful shutdown

### ISSUE THREAD

**Issue by keiranjprice101** [fiaisis/run-detection#26]
Implement a graceful shutdown. The key things to make sure is, any active messages are not ack'd or specifically ack'd, and that the queue connections are closed.

Ensuring that any exception if it would otherwise cause the program to close, crash, stop etc. will first of all close the stomp connection to ActiveMQ.

**Comment by Pasarus** [comment]
Might be a problem with memphis, do a quick investigation.
