### ISSUE TITLE
Check black as part of CI for dependabot

### ISSUE THREAD

**Issue by keiranjprice101** [fiaisis/run-detection#48]
Check that black runs ok for when dependabot updates. Possibly add a non CI failing step to run a black but not fail on diff.

e.g. `black --diff rundetection` This will always exit as 0 as long as black runs complete even without exceptions raised.

This will allow us to ensure that a dependabot black update passes, without having to wait and see if the auto-formatting action runs.

**Comment by Pasarus** [comment]
Migrate to using black in PRs instead of on main pushes.
